name: ens_dart
description: A dart library that wraps the Ethereum Name Service. It enables users and developers to use human-friendly names in place of error-prone hexadecimal addresses, content hashes, and more.
version: 1.0.0
homepage: https://github.com/Zfinix/ens_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  convert: ^3.0.1
  dotenv: ^4.2.0
  fast_base58: ^0.2.1
  flutter:
    sdk: flutter
  http: ^1.2.1
  sha3: ^0.2.0
  web3dart: ^2.7.2
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
